### ISSUE TITLE
关于模型预测的infer接口

### ISSUE THREAD

**Issue by bestpredicts** [guoday/ctrNet-tool#2]
是不是可以只传入一个参数,比如 preds=model.infer(dev_data=(test[features]))  我看代码示例dev_data需要传入label?   还是说dev_data，必须传入label像这样 preds=model.infer(dev_data(test[features],test['HasDetections']))

**Comment by guoday** [comment]
实际上是不需要传label的。我也发现了这么问题，代码还没修改回来，后续会修改回来的。现在的代码不传label的话会报错
