### ISSUE TITLE
TypeError: argument of type 'HParams' is not iterable

### ISSUE THREAD

**Issue by tianshuaifei** [guoday/ctrNet-tool#4]
第一次开源https://www.kaggle.com/guoday/nffm-baseline-0-690-on-lb
的时候能正常使用
最近开源https://www.kaggle.com/guoday/xdeepfm-baseline之后，
重新运行代码，运行报错了，
python 3.6
tensorflow-gpu 1.4.0,

Traceback (most recent call last):
  File "gd_nffm.py", line 167, in <module>
    dev_data=(train.iloc[dev_index][features], train.iloc[dev_index]['HasDetections']))
  File "/home/yuqing/tsf/kaggle/mmp/models/nffm.py", line 106, in train
    if idx*hparams.batch_size>=len(train_data[0]) or ('steps' in hparams and hparams.steps==idx):
TypeError: argument of type 'HParams' is not iterable

**Comment by guoday** [comment]
是的，我加了新的代码，在1.4.0不支持，我估计要升级到1.6.0。我修改一下使得支持1.4.0

**Comment by guoday** [comment]
已经修复
