### ISSUE TITLE
base_model 正则化损失_cross_l_loss计算  是否有问题

### ISSUE THREAD

**Issue by mathlf2015** [guoday/ctrNet-tool#5]
脚本 baseline_model 第76,77行

def _cross_l_loss(self, hparams):
    cross_l_loss = tf.zeros([1], dtype=tf.float32)
    for param in self.cross_params:
        cross_l_loss = tf.add(cross_l_loss, tf.multiply(hparams.cross_l1, tf.norm(param, ord=1)))
        cross_l_loss = tf.add(cross_l_loss, tf.multiply(hparams.cross_l2, tf.norm(param, ord=1)))
    return cross_l_loss 
    

加了两次L1损失，而第二个参数是hparams.cross_l2

**Comment by guoday** [comment]
这个是之前的代码，我并没有使用，但确实是有这个问题

**Comment by guoday** [comment]
目前已经把base_model没有用到函数和代码全删了，你可以再看下

**Comment by mathlf2015** [comment]
好的，学习大佬代码中。。
