### ISSUE TITLE
请问训练集和验证集的logloss都在降低，但是auc为啥也越来越低了啊，偏差还挺大

### ISSUE THREAD

**Issue by whoami-zy** [guoday/ctrNet-tool#8]
poch 0 step 100 lr 0.001 logloss 0.365111 gN 0.56, Wed Jul  3 17:12:50 2019
  epoch 0 step 200 lr 0.001 logloss 0.191605 gN 0.28, Wed Jul  3 17:13:58 2019
  epoch 0 step 300 lr 0.001 logloss 0.182971 gN 0.25, Wed Jul  3 17:15:06 2019
  epoch 0 step 400 lr 0.001 logloss 0.175328 gN 0.23, Wed Jul  3 17:16:19 2019
  epoch 0 step 500 lr 0.001 logloss 0.167133 gN 0.21, Wed Jul  3 17:17:36 2019
# Epcho-time 355.16s Eval AUC 0.982286. Best AUC 0.982286.
  epoch 0 step 600 lr 0.001 logloss 0.173233 gN 0.20, Wed Jul  3 17:19:29 2019
  epoch 0 step 700 lr 0.001 logloss 0.169078 gN 0.19, Wed Jul  3 17:20:41 2019
  epoch 0 step 800 lr 0.001 logloss 0.166135 gN 0.18, Wed Jul  3 17:21:52 2019
  epoch 0 step 900 lr 0.001 logloss 0.161865 gN 0.17, Wed Jul  3 17:23:02 2019
  epoch 0 step 1000 lr 0.001 logloss 0.158251 gN 0.17, Wed Jul  3 17:24:11 2019
# Epcho-time 750.18s Eval AUC 0.464652. Best AUC 0.982286.
  epoch 0 step 1100 lr 0.001 logloss 0.161384 gN 0.17, Wed Jul  3 17:25:25 2019
  epoch 0 step 1200 lr 0.001 logloss 0.158918 gN 0.16, Wed Jul  3 17:26:41 2019
  epoch 0 step 1300 lr 0.001 logloss 0.157845 gN 0.15, Wed Jul  3 17:28:13 2019
  epoch 0 step 1400 lr 0.001 logloss 0.154907 gN 0.15, Wed Jul  3 17:29:35 2019
  epoch 0 step 1500 lr 0.001 logloss 0.157655 gN 0.15, Wed Jul  3 17:30:52 2019

**Comment by dmlan** [comment]
nffm模型，其他比赛数据集，也出现了这个问题。

**Comment by guoday** [comment]
这个有可能过拟合了，验证集的loss没有打印出来，打印出来的是训练集的loss
